<a href="https://colab.research.google.com/github/humanvarun/humanvarun/blob/main/basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Perceptron

###Importing Libraries

In [6]:
from numpy import array #For Array Initialization
from numpy import random #For Randomly choosing Numbers
from numpy import dot #For Doing DOT Product
from random import choice
import numpy as np #Import numpy for array operations

###Activation Function

In [7]:
activationFn = lambda x: 0 if x < 0 else 1 #step activation function (if i/p is negative o/p is 0 else 1)

###initializing Dataset

In [14]:
dataset = [
    (array([0,0,1]), 0), #array([x,y,b],e) x,y=Input , b=bias, e=Expected O/P to validate
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]
print(dataset)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


###Initializing Random numbers for WEIGHTS

In [19]:
weights = random.rand(3)

###Initializing additional variables

In [10]:
r = 0.2 #learning Rate
n = 100 #Number of Iteration

###Training our Model

In [28]:
for j in range(n):
    x, expected = choice(dataset) #random input set, Includes repeated numbers
    #print(x,expected)
    result = dot(weights, x) #dot product of the input and the weight vectors
    err = expected-activationFn(result)
    weights += r * err * x #calculate the correction factor, added to weights to improve o/p in next iteration
    #If the expected value is bigger, the weights should be increased, and if expected value is smaller, the weights should be decreased

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4, 2) + inhomogeneous part.

###Evaluating Model

In [29]:
for x, _ in dataset:
    result = dot(x, weights)
    print("Input: {}  ResultBAFn: {} ResultAFn: {}".format(x[:2], round(result,3), activationFn(result)))

Input: [0 0]  ResultBAFn: 0.481 ResultAFn: 1
Input: [0 1]  ResultBAFn: 0.567 ResultAFn: 1
Input: [1 0]  ResultBAFn: 0.507 ResultAFn: 1
Input: [1 1]  ResultBAFn: 0.593 ResultAFn: 1
